version: '2'

services:
  web:
    restart: always
    build: ./flaskapp
    expose:
      - "8000"
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
      
  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"
  
  postgres:
    restart: always
    build: ./postgresql
    volumes_from:
      - data
    ports:
      - "5432:5432"