"""empty message

Revision ID: 26ace179993f
Revises: 025fdbbef758
Create Date: 2019-04-24 01:42:42.492093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ace179993f'
down_revision = '025fdbbef758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('edit_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('edit_uid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'edit_uid')
    op.drop_column('user', 'edit_date')
    op.drop_column('user', 'create_date')
    # ### end Alembic commands ###
