"""empty message

Revision ID: 3442347b2f0a
Revises: b2495ef85dc0
Create Date: 2019-04-25 02:25:51.703997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3442347b2f0a'
down_revision = 'b2495ef85dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'loan', 'user', ['create_uid'], ['id'])
    op.create_foreign_key(None, 'loan', 'user', ['edit_uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_constraint(None, 'loan', type_='foreignkey')
    # ### end Alembic commands ###
