"""empty message

Revision ID: a14364afa4b0
Revises: 3442347b2f0a
Create Date: 2019-04-25 02:29:00.799361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14364afa4b0'
down_revision = '3442347b2f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('loan_create_uid_fkey', 'loan', type_='foreignkey')
    op.drop_constraint('loan_edit_uid_fkey', 'loan', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('loan_edit_uid_fkey', 'loan', 'user', ['edit_uid'], ['id'])
    op.create_foreign_key('loan_create_uid_fkey', 'loan', 'user', ['create_uid'], ['id'])
    # ### end Alembic commands ###
