"""empty message

Revision ID: b2495ef85dc0
Revises: c24b69987b0f
Create Date: 2019-04-25 02:23:33.828343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2495ef85dc0'
down_revision = 'c24b69987b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loan', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_column('loan', 'user')
    # ### end Alembic commands ###
