"""empty message

Revision ID: b669a8ca6fbe
Revises: a14364afa4b0
Create Date: 2019-04-25 03:15:06.235730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b669a8ca6fbe'
down_revision = 'a14364afa4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('emi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'emi')
    # ### end Alembic commands ###
