"""empty message

Revision ID: ef253c25c195
Revises: b669a8ca6fbe
Create Date: 2019-04-25 03:20:30.357824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef253c25c195'
down_revision = 'b669a8ca6fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('total_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'total_amount')
    # ### end Alembic commands ###
